---
version: '2'
services:  
  zookeeper:
    image: jplock/zookeeper:3.4.8

  kafka:
    image: ches/kafka:0.10.0.0
    links:
    - zookeeper:zookeeper
    environment:
      ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
